apiVersion: v1
kind: ConfigMap

metadata:
  name: shopsphere-config
  namespace: shopsphere

data:
  POSTGRES_DB: "shopsphere"
  POSTGRES_USER: "postgres"

  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"

  APP_ENV: "production"